version: '3'
services:
    db: 
      image: mysql:8.0
      restart: always
      environment: 
        - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        - MYSQL_ROOT_DATABASE=${DB_DATABASE}
      ports:
        - "3307:3306"
      expose:
        - 3306

    s-group-app:
      depends_on:
        - db
      image: baocules/s-group-app:latest
      restart: always
      environment:
        - DB_HOST=db
        - DB_PORT=3306
      ports:
        - "3000:3000"
