name: CI/CD pipeline

# Khi xảy ra sự kiện pull request vào nhánh develop -> thực hiện
on:
  pull_request:
    branches:
      - main

jobs:
  # Job 1: Build và test trên máy ảo Ubuntu
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      # Sử dụng action để checkout code từ repo vào máy ảo
      - name: Checkout code
        uses: actions/checkout@v2

      # Login Docker Hub
      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build và test image được build ra bởi Docker
      - name: Build and test image by Docker
        run: |
          sudo docker build -t s-group-app .
          sudo docker run s-group-app npm test

      # Push image to Docker Hub
      - name: Push image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/s-group-app:latest

  # Job 2: Deploy lên EC2
  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest

    steps:
      # Đăng nhập vào Docker và pull image về và run
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/s-group-app:latest
            sudo docker stop ubuntu-s-group-app-1 || true
            sudo docker rm ubuntu-s-group-app-1 || true
            sudo docker run -d -p 3000:3000 --name ubuntu-s-group-app-1 ${{ secrets.DOCKERHUB_USERNAME }}/s-group-app:latest
