name: CI/CD pipeline

# Khi xay ra su kien pull request vao nhanh develop -> thuc hien
on:
  pull_request:
    branches:
      - develop

jobs:
  # Job 1: build va test tren may ao ec2
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      # Su dung action de copy code tu repo vao may ao ec2
      - name: checkout code
        uses: actions/checkout@v2

      # Login dockerhub
      - name: login Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # Build va test img duoc build ra boi Docker
      - name: build and test image by Docker
        run: |
          docker build -t s-group-app .
          docker run s-group-app npm test
        
      # Push image to Dockerhub
      - name: push image to Dockerhub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/reactjs-basic:latest

  # Job 2: Len ec2 deploy
  deploy:
    needs: build_and_test
    runs_on: ubuntu_latest

    steps:
      # Dang nhap vao docker va pull image ve va run
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/s-group-app:latest
            sudo docker stop ubuntu-s-group-app-1
            sudo docker rm ubuntu-s-group-app-1
            docker run -d -p 3000:3000 --name ubuntu-s-group-app-1 ${{ secrets.DOCKERHUB_USERNAME }}/s-group-app:latest 

     

